name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js (optional, if Node.js is needed)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Deploy to GitHub Pages
      uses: actions/upload-pages-artifact@v1

    - name: Publish GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
